name: Coverage

on:
  pull_request:
    branches:
      - master
      - main
      - development
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.4
        with:
          package-manager: pnpm
          working-directory: "./packages/next-api-compose/"
          test-script: pnpm jest --json --coverage --testLocationInResults --outputFile=report.json
